# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: L_manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - L_joint_1
    - L_joint_2
    - L_joint_3
    - L_joint_4
    - L_joint_5
    - L_joint_6
    - R_joint_1
    - R_joint_2
    - R_joint_3
    - R_joint_4
    - R_joint_5
    - R_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: L_manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - L_joint_1
      - L_joint_2
      - L_joint_3
      - L_joint_4
      - L_joint_5
      - L_joint_6
  - name: R_manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
L_manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - L_joint_1
    - L_joint_2
    - L_joint_3
    - L_joint_4
    - L_joint_5
    - L_joint_6
  gains:
    L_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
R_manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - R_joint_1
    - R_joint_2
    - R_joint_3
    - R_joint_4
    - R_joint_5
    - R_joint_6
  gains:
    R_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

      d: 1
      i: 1
      i_clamp: 1
    R_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
