controller_list:
  - name: fake_L_manipulator_controller
    joints:
      - L_joint_1
      - L_joint_2
      - L_joint_3
      - L_joint_4
      - L_joint_5
      - L_joint_6
  - name: fake_R_manipulator_controller
    joints:
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
  - name: fake_manipulator_controller
    joints:
      - L_joint_1
      - L_joint_2
      - L_joint_3
      - L_joint_4
      - L_joint_5
      - L_joint_6
      - R_joint_1
      - R_joint_2
      - R_joint_3
      - R_joint_4
      - R_joint_5
      - R_joint_6
initial:  # Define initial robot poses.
  - group: L_manipulator
    pose: home
  - group: R_manipulator
    pose: home
  - group: manipulator
    pose: home